### ISSUE TITLE
Have you considered utilizing Pydantic? 

### ISSUE THREAD

**Issue by judahrand** [marcosschroh/dataclasses-avroschema#120]
This is really a fairly open ended question but I was wondering if this project could effectively wrap (or seamlessly integrate with) Pydantic. This could be as simple as seeing if it is possible to use their `dataclass` implementation or we could allow inheritance from their `BaseModel`?

Any thoughts on integrating with Pydantic to allow for 'smart' type inferences and checking on the Python side?

**Comment by marcosschroh** [comment]
Hi @judahrand,

Yes, I have considering using it. It can be useful because I think we can get the `json schema` as well and also for validation purpose. First, I think it would to wise to add the `fastavro validation` (executed before an instance is created) and then add the integration with `pydantic`. With the integration we need to be a bit careful with the `validation` and the `json` method. `AvroModel` has `to_json` and `BaseModel` has `json`

Also, I think we should give the possibility to the end use to decide whether to use the integration with `pydantic` or not. I think we can create an extra class, e.g:

```python
class AvroDanticModel(AvroModel, BaseModel):  # just a random name. Maybe we will have conflicts with the multiple inheritance. 
    ...
```

What do you think?

**Comment by marcosschroh** [comment]
related to https://github.com/marcosschroh/dataclasses-avroschema/pull/163
