### ISSUE TITLE
Respect original schema field ordering

### ISSUE THREAD

**Issue by robbertvanwaveren** [marcosschroh/dataclasses-avroschema#345]
**Describe the bug**
The field ordering of the original schema is not used to generate a model. Instead avro unions (optional fields) are put last.

This means that:

1. serialized binary avro has the wrong order (cannot be deserialized with just the original schema)
2. using the avro_schema() function of a generated model does not produce the original schema 

**To Reproduce**

```
{
  "type": "record",
  "name": "Message",
  "fields": [
    {
      "name": "a",
      "type": "string"
    },
    {
      "name": "b",
      "type": "long"
    },
    {
      "name": "c",
      "type": [
        "null",
        "string"
      ]
    },
    {
      "name": "d",
      "type": "string"
    }
  ]
}
```

will result a model with fields in different order.

**Expected behavior**

The avro_schema as well as the resulting binary avro to be binary compatible with the original schema.

**Comment by marcosschroh** [comment]
Hi @robbertvanwaveren,

This is a tricky one because you can not have optional fields before required fields in a python class. For example, The following python `dataclass` is invalid:

```python
import dataclasses
from dataclasses_avroschema import AvroModel


@dataclasses.dataclass
class UserAdvance(AvroModel):
    name: str = "bond"
    last_name: str 
```

which raises: `TypeError: non-default argument 'last_name' follows default argument`

Optional fields must be at the end of the `python class` and also at the end of the `avro schema` in order to make ir work.  If you generate the `avro schema` from a python class using this library then the order is guarantee. If the schema was generated by other tool or manually then it won't work. I will advise you to create a new schema to match the python class.

**Comment by marcosschroh** [comment]
Yes, usually the schema comes first. Looking forward to see the PR!

**Comment by marcosschroh** [comment]
@robbertvanwaveren how is it going with the PR? I can also implement a fix for this issue.
