### ISSUE TITLE
Support `Literal` type construct as an inline `enum` definition

### ISSUE THREAD

**Issue by Prometheus3375** [marcosschroh/dataclasses-avroschema#425]
**Is your feature request related to a problem? Please describe.**

In order to define `enum` avro type, one should create `Enum` subclass and describe all possible values there.
This is a very verbose way to define an `enum` type and I would like to have a more concise solution.
In addition, deserialization produces `Enum` instances, but in some situations I would like to have raw values immediately instead of wrappers around them.

**Describe the solution you'd like**
The solution is to make use of `Literal` type construct. Observe:

```python
from dataclasses_avroschema import AvroModel
from dataclasses import dataclass
from enum import Enum


class StreetLightColor(Enum):
    GREEN = 'GREEN'
    YELLOW = 'YELLOW'
    RED = 'RED'


@dataclass
class Data(AvroModel):
    street_light_color: StreetLightColor
```
vs.
```python
from dataclasses_avroschema import AvroModel
from dataclasses import dataclass
from typing import Literal


@dataclass
class Data(AvroModel):
    street_light_color: Literal['GREEN', 'YELLOW', 'RED']
```

One of the intrinsic features `Literal` has is the uniqueness of passed strings which is required by `enum` avro type. `Literal['GREEN', 'YELLOW', 'YELLOW', 'RED']` is the same as `Literal['GREEN', 'YELLOW', 'RED']`. To achieve the same result, `Enum` subclasses must be decorated with `enum.unique`.

Since `Literal` arguments are strings, then its deserialization will also produce strings, not wrappers around them.

**Describe alternatives you've considered**
Alternative solution already exists, it is `Enum` subclasses.

**Additional context**
`enum` avro type can have additional fields like `namespace`. Currently, one can define class member `Meta` to `Enum` subclasses to add these fields. To achieve the same for `Literal`, it can be wrapped with `Annotated`: `Annotated[Literal[...], Meta]` or `Annotated[Literal[...], dict(namespace='StreetLightColor.v1')]`.

**Comment by OffByOnee** [comment]
@Prometheus3375 I came across a need for `typing.Literal` as well and I've started working on adding support for it. Should have a PR out in the next day or two

**Comment by OffByOnee** [comment]
@marcosschroh do you think we could get this one merged before dropping support for pydantic v1?

**Comment by OffByOnee** [comment]
@Prometheus3375 thinking about your last paragraph:

> Additional context
> enum avro type can have additional fields like namespace. Currently, one can define class member Meta to Enum subclasses to add these fields. To achieve the same for Literal, it can be wrapped with Annotated: Annotated[Literal[...], Meta] or Annotated[Literal[...], dict(namespace='StreetLightColor.v1')].

I can't think of any metadata fields that should be added for `Literal` since the metadata really applies to underlying types. Consider the following:
```py
from dataclasses_avroschema import AvroModel
from dataclasses import dataclass
from typing import Literal

class Count(Enum):
    ONE = '1'
    TWO = '2'

@dataclass
class Data(AvroModel):
    count: Literal[1, Count.ONE]
```
The schema will have `count` as a union of the literal types (since that field annotation is shorthand for `typing.Union[typing.Literal[1], typing.Literal[Count.ONE]]`). `namespace` metadata is only applicable to enums, so it would apply when `count=Count.ONE` since `count` would be serialized as an instance of `Count`, but not for `count=1` when it would be serialized as an `int`.

**Comment by Prometheus3375** [comment]
@OffByOnee I have suggested to treat `Literal` as a shorthand for `enums`. In that case `Literal` can accept only strings since avro enums can be only strings. Any other type should lead to an error.

> (since that field annotation is shorthand for `typing.Union[typing.Literal[1], typing.Literal[Count.ONE]]`

This is true only for type checkers. At runtime these annotations are not equal.

```python
>>> Literal[1, 2, 3] == Union[Literal[1], Literal[2], Literal[3]]
False
```

`Literal` stores all passed arguments in `__args__` (or call `typing.get_args`). They should be checked to be strings. The only difference with current `enum` implementation is the fact that deserialization produces strings instead of enum objects.

**Comment by OffByOnee** [comment]
@Prometheus3375 Ah sorry, I misunderstood. It seems counterintuitive to me to repurpose a built-in as shorthand for another built-in. Maybe the shorthand could be done with either a custom syntax for Enum (something like `Enum['GREEN', 'YELLOW', 'RED']`) or a type that's custom to this library, so that we don't eliminate support for `Literal` as defined by the PEP? Note also that `pydantic` follows the PEP definition for how it handles literals, so going down the repurposing route could cause integration problems for `AvroBaseModel`.

This is @marcosschroh's project though, so I'll step aside and let him chime in.

**Comment by marcosschroh** [comment]
I agree with @OffByOnee 

If we use only `Literal` as a shorthand for `enums` then we do not support cases like `Literal[1, 2, 3]`, `Literal["Batman"]` or Literal[1, 2, 3, "Batman"] which are valid and they should produce avro types `long`, `str` and ["long", "str"] respectively. 

If you see `Literal['GREEN', 'YELLOW', 'RED']`,  Is it an `enum` or `string`?
