### ISSUE TITLE
Generated avro schema for nullable fields is dependent on the exact implementation

### ISSUE THREAD

**Issue by Relativity74205** [marcosschroh/dataclasses-avroschema#627]
Actually, I am not 100 % sure, if this is a bug or working as intended.

**Describe the bug**
Observed problem: Depending how a nullable field is defined in a dataclass, the avro schema is generated differently, which has consequences for the produced to Kafka.

**To Reproduce**
The documented way to create a nullable attribute in a dataclass is `address: str = None`. Then the corresponding avro field is
```
        {
            "name": "address",
            "type": [
                "null",
                "string"
            ],
            "default": null
        }
```
`address: None | str` generates the same result, however, without the default.

However, when using `address: Optional[str]` (or `address: str | None`), then we get
```
        {
            "name": "address",
            "type": [
                "string",
                "null"
            ]
        },
```
Note, that in this cases the non-null type in the union list comes first. Before, the null type came first. According to avro spec, "[...] the 'null' is usually listed first [...]" https://avro.apache.org/docs/1.11.1/specification/#unions.

And this causes problems for the confluent python library, which generates the following message, when the non-null type in the union list comes first.
```
{"address": {"string": "foo"}}
```
and not simply `{"address": "foo"}`.

**Expected behavior**
Regardless of the exact implementation of a nullable attribute, the type should be `"type": ["null", "string"]` to prevent problems at other places.

However, as stated at the beginning, I am note sure, if this is actually a bug and rather a problem of the producer client. However, I have seen already other (non confluent producers) which behaved the same, when a type was defined as `["string", "null"]`.

**Comment by marcosschroh** [comment]
Hi @Relativity74205 this is the expected behavior. 

`avro unions` can have any order, so we should have a way to represent any order. Some clarifications:

1. Why `Optional[str]`  (`str | None`) generates `[string, null]`? It is because [python works in this way](https://docs.python.org/3/library/typing.html#typing.Optional). It is also in the [docs](https://marcosschroh.github.io/dataclasses-avroschema/complex_types/#unions-with-typingoptional)
2. Are both valid options? Yes, because it is allowed, then you should be careful when designing `avro schemas`. If you have an `union` and it has a default value, then the first element MUST match the default value type (This is really important!!)
3. Usually, (I will dare to say always) we see `null` first in the `union` with a `default value `null`. The reason for this is to allow the producer to skip the optional field, then the consumer will not crash.
4. Following your example, `{"address": {"string": "foo"}}` I think you are using the `avro-json` representation. When you use this, then the type is also specified, otherwise `avro` will not be able to guess the types. You can find examples and the documentation [Encoding for unions with avro-json](https://marcosschroh.github.io/dataclasses-avroschema/serialization/#encoding-for-unions-with-avro-json)

I hope it is clear.

**Comment by AS-auxmoney** [comment]
@marcosschroh Yes, the issue can be closed. Thanks for your assistance.
