### ISSUE TITLE
How to parse json string back to AvroModel

### ISSUE THREAD

**Issue by RuiLoureiro** [marcosschroh/dataclasses-avroschema#638]
Hi! I'm trying to initialize an `AvroModel` from a json string.

I tried using `parse_obj`, but the strings corresponding to `datetime` are not parsed into a `datetime` object.

## Example
```python
import json
import dataclasses
from datetime import datetime

from dataclasses_avroschema.schema_generator import AvroModel


@dataclasses.dataclass
class MyModel(AvroModel):
    a: str
    b: datetime

    class Meta:
        namespace = "my.namespace"

m = MyModel(a="123", b=datetime.now())

parsed = MyModel.parse_obj(json.loads(m.to_json()))

# prints 'MyModel(a='123', b='2024-05-24T12:28:49')'
print(parsed)
```

Is this expected behavior? And is there any alternative way to achieve this?

**Comment by marcosschroh** [comment]
Hi,

Ideally we want to have the original object. The problem is that `dataclasses` are not really smart, then we are using [dacite](https://github.com/konradhalas/dacite) to make the conversion from `dict` to class instances. To solve your problem right away you can use [custom dacite config](https://marcosschroh.github.io/dataclasses-avroschema/records/?h=dacite#override-dacite-config) using `type_hooks`:

```python
import json
import dataclasses
from datetime import datetime

from dataclasses_avroschema.schema_generator import AvroModel

def parse_datetime(value):
     return datetime.strptime(value, "%Y-%m-%dT%H:%M:%S")



@dataclasses.dataclass
class MyModel(AvroModel):
     a: str
     b: datetime

     class Meta:
         namespace = "my.namespace"
         dacite_config = {"type_hooks": {datetime: parse_datetime}}

m = MyModel(a="123", b=datetime.now())

print(MyModel.parse_obj(json.loads(m.to_json())))

Out[33]: MyModel(a='123', b=datetime.datetime(2024, 5, 24, 16, 29, 3))
```

I will add the hook in the library so it will be easier for end users. You need to take into account that if the `datetime string format` changes then it won't work.

**Comment by RuiLoureiro** [comment]
Thank you for the quick reply @marcosschroh.
I added the `dacite` type hooks and it works as expected, so I'm closing the issue

**Comment by marcosschroh** [comment]
@RuiLoureiro You're welcome. I have added the missing `dacite hooks`. If you update to the latest version (`0.60.0`) you can remove your custom hook (everything should work effortless from end user point of view)
