### ISSUE TITLE
Enum with both type default and field default generates invalid python

### ISSUE THREAD

**Issue by ericdevries** [marcosschroh/dataclasses-avroschema#665]
**Describe the bug**
When an enum field has both a type level default and a field level default, the python code generated is invalid.

**To Reproduce**
The code below shows the schema, the code to generate it and (part of) the generated output.

```python
from dataclasses_avroschema import ModelGenerator, ModelType

model_generator = ModelGenerator()

schema = {
    "schemaVersion": "2.0.0",
    "type": "record",
    "name": "Message",
    "namespace": "a.b.message",
    "doc": "Example",
    "fields": [
        {
            "name": "measuringPeriod",
            "type": {
                "type": "enum",
                "name": "AccumulatorMeasuringPeriod",
                "symbols": ["None", "Unknown"],
                "default": "Unknown",  # type default
            },
            "default": "None",  # field default
        }
    ],
}

result = model_generator.render(schema=schema, model_type=ModelType.DATACLASS.value)

# OUTPUT

@dataclasses.dataclass
class Message(AvroModel):
    """
    Example
    """
    measuringPeriod: AccumulatorMeasuringPeriod = AccumulatorMeasuringPeriod.UNKNOWN = AccumulatorMeasuringPeriod.NONE

    class Meta:
        namespace = "a.b.message"


```

**Expected behavior**
Not entirely sure what the expected output would be, but I believe the type level default is to deal with newly added enum values that the reader does not know about. The field level default should be used by the reader if the field does not exist in the reader schema. 

In the case above, the field does exist in the reader schema so I would expect the type level default to be used, so "Unknown".

**Comment by marcosschroh** [comment]
Hi @ericdevries 

Thanks for reporting the issue. I think the expecting `default` value in the python class must be `Unknown`. 
I checked the `avro documentation` and you are correct: `enum type level default value is to deal with newly added symbols that the reader does not know about`. This is for `forwards compatibility` introduced in `avro 1.9.0` (really hard to find this by the way). 

Long story short, a schema can be like this:

```json
{
  "type": "record",
  "name": "MyRecord",
  "fields": [
    {
      "name": "my_field",
      "type": {
        "type": "enum",
        "name": "MyEnum",
        "symbols": [
          "a",
          "b",
          "Unknown"
        ],
        /* 
         * Symbol default - for forwards compatibility - 
         * new in Avro 1.9.0
         */
         "default": "Unknown"  
      },
      /*
       * Field default - for handle backwards compatibility
       */ 
       "default": "Unknown"    
    },
```

In my opinion BOTH default values should be the same to have `forwards` and `backwards` compatibility. In your example you used `Unknown` and `None` which can lead to super confusing scenarios

**Comment by robbertvanwaveren** [comment]
How did you reach the conclusion about compatibility and confusion if I may ask?

1. The field-level default is there to create messages more easily and assign a typical value to a field if the field is not send over the wire. Perfectly usable by all client in all scenarios.
2. The "Unknown" is there to inform the client, a value actually WAS send over the wire but the client does not understand that value yet. Only usable by clients who do not need to know the value of that field. Clients who do use the field should not attempt to process the record.

Hopefully this makes it a bit more clear why it is in fact important for clients to actually see different values in each use-case.

**Comment by marcosschroh** [comment]
Of course you can ask @robbertvanwaveren 

I think there is not doubts about point 1. Always try to use `default values` at field level so a new schema  will `FULL COMPATIBLE`.

Now about point 2 (type level  default for `enum`). This change was introduced on [avro 1.9.0](https://avro.apache.org/docs/1.9.0/spec.html#Enums), you can compare the documentation with previous versions. 

The specification says: `default: A default value for this enumeration, used during resolution when the reader encounters a symbol from the writer that isn't defined in the reader's schema (optional). The value provided here must be a JSON string that's a member of the symbols array. See documentation on schema resolution for how this gets used.
`.  Let's make an example:

We have our schema, called `v1`:

```python
v1 = {
    "type": "record", 
    "name": "User", 
    "fields": [
        {
            "name": "name", 
            "type": {
                "type": "enum", 
                "name": "MyEnum", 
                "symbols": ["FLASH", "BATMAN"]
            }, 
            "default": "FLASH"
        }
    ]
}
```

If I introduce a new schema called v2 with an extra `symbol` (in this case `SUPERMAN`), what is their `COMPATIBILITY`?

```python
v2 = {
    "type": "record", 
    "name": "User", 
    "fields": [
        {
            "name": "name", 
            "type": {
                "type": "enum", 
                "name": "MyEnum", 
                "symbols": ["FLASH", "BATMAN", "SUPERMAN"],
            },
            "default": "FLASH"
        }
    ]
}
```

`BACKWARDS`: Yes, because If an event is produced with `v1` it can be read with `v2`
`FORWARD`: No, because if an event is produced with `v2` it could not be read using `v1` If `SUPERMAN` is sent.

To solve `FORWARD` compatibility, a `default value at enum level` can be introduced on `v1`. If `v1` would have look like the following schema:


```python
schema = {
    "type": "record", 
    "name": "User", 
    "fields": [
        {
            "name": "name", 
            "type": {
                "type": "enum", 
                "name": "MyEnum", 
                "symbols": ["FLASH", "BATMAN"],
                "default": "FLASH"  # THIS HAS BEEN ADDED
            }, 
            "default": "FLASH"
        }
    ]
}
```
Then we achieve `FORWARD` compatibility as well. If an event is produced with `v2` with `SUPERMAN` then it can be read using `v1`, because the result will be the default (enum default, not field default)`FLASH`.

Even thought this is great because we achieve `FULL COMPATIBILITY`, for me it introduces confusion (it is a personal opinion). I think I prefer the code to crash rather than send an event with a value an the consumer gets a different one. 

Regardless my opinion, it is something that `dataclasses-avroschemas` must support because it is a valid `avro feature`. I will work in a PR to add `default enum values`, looking something like:

```python
class FavoriteColor(enum.Enum):
    BLUE = "Blue"
    YELLOW = "Yellow"
    GREEN = "Green"

    class Meta:
        doc = "A favorite color"
        namespace = "some.name.space"
        aliases = ["Color", "My favorite color"]
        default = "BLUE"  # NEW FEATURE!! 
```

**Comment by robbertvanwaveren** [comment]
I think we kinda agree. It is indeed a bad thing for a client to USE a different value then was actually send. In fact I strongly recommend to never use an enum-level default that makes any functional sense, in order for clients to distingious this scenario and thus be able to choose to not process it. 

So support for different default values at both levels would be to help preventing clients from unknowingly receive and process enum-symbols that they do not actually know. The small functional difference between failing/crashing-at-parse and conciously choosing not to process, is to prevent clients that simply do not use/care about the field from failing to parse.

**Comment by marcosschroh** [comment]
You can check the [documentation](https://marcosschroh.github.io/dataclasses-avroschema/complex_types/#enums-type-level-default)

**Comment by ericdevries** [comment]
Thank you very much for solving this issue
