### ISSUE TITLE
Test fixtures are dangerously specified

### ISSUE THREAD

**Issue by danieltahara** [marcosschroh/dataclasses-avroschema#70]
**Describe the bug**

In the test field type fixtures, what is "tuple" notation in some places is iterator notation in others. For example, this (and all other instances of ( ... for x in y ) are iterators, not tuples): https://github.com/marcosschroh/dataclasses-avroschema/blob/master/tests/fields/consts.py#L92

This means if you ever use the field fixture to parametrize > 1 test like https://github.com/marcosschroh/dataclasses-avroschema/blob/3e35968350c45e5c42eb64dce7deb0514e5cf889/tests/fields/test_complex_types.py, the second test will have no parametrized instances, b/c the iterator will yield no values the second usage.

**To Reproduce**
Duplicate any of the tests in test_complex_types.py, and change both bodies to `assert False`. One set of tests will "pass" b/c there will be no test instances.

**Expected behavior**

**Comment by marcosschroh** [comment]
Hi @danieltahara , is a good point and thanks for the remark. Having `generators` for now is fine because we need them only once, but if we want to reuse them definitely we should need to change them to a `container` object. Performance wise is practically the same, so if you want feel free to send a PR and change the `generators` into `containers`
